import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        {
            itemId: 'F001',
            name: 'Masala Dosa',
            price: 40.00,
            category: 'breakfast',
            description: 'Crispy rice crepe with spiced potato filling',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F002',
            name: 'Idli Sambar',
            price: 30.00,
            category: 'breakfast',
            description: 'Steamed rice cakes with lentil curry',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F003',
            name: 'Poha',
            price: 25.00,
            category: 'breakfast',
            description: 'Flattened rice with peanuts and spices',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F004',
            name: 'Upma',
            price: 20.00,
            category: 'breakfast',
            description: 'Semolina porridge with vegetables',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F005',
            name: 'Veg Fried Rice',
            price: 60.00,
            category: 'lunch',
            description: 'Stir-fried rice with mixed vegetables',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F006',
            name: 'Dal Rice',
            price: 50.00,
            category: 'lunch',
            description: 'Lentil curry with steamed rice',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F007',
            name: 'Chole Bhature',
            price: 70.00,
            category: 'lunch',
            description: 'Spiced chickpeas with fried bread',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F008',
            name: 'Veg Biryani',
            price: 80.00,
            category: 'lunch',
            description: 'Aromatic rice with vegetables',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F009',
            name: 'Paneer Butter Masala',
            price: 90.00,
            category: 'dinner',
            description: 'Cottage cheese in creamy tomato gravy',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F010',
            name: 'Aloo Paratha',
            price: 45.00,
            category: 'dinner',
            description: 'Stuffed flatbread with potato filling',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F011',
            name: 'Rajma Rice',
            price: 55.00,
            category: 'dinner',
            description: 'Kidney beans curry with rice',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F012',
            name: 'Tea',
            price: 10.00,
            category: 'beverage',
            description: 'Hot Indian masala chai',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F013',
            name: 'Coffee',
            price: 15.00,
            category: 'beverage',
            description: 'Hot filter coffee',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F014',
            name: 'Buttermilk',
            price: 20.00,
            category: 'beverage',
            description: 'Refreshing spiced yogurt drink',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F015',
            name: 'Lime Soda',
            price: 25.00,
            category: 'beverage',
            description: 'Fresh lime with soda',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F016',
            name: 'Samosa',
            price: 15.00,
            category: 'snacks',
            description: 'Crispy fried pastry with spiced filling',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F017',
            name: 'Pakora',
            price: 20.00,
            category: 'snacks',
            description: 'Deep-fried vegetable fritters',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F018',
            name: 'Vada Pav',
            price: 30.00,
            category: 'snacks',
            description: 'Spiced potato fritter in a bun',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            itemId: 'F019',
            name: 'Bread Pakora',
            price: 25.00,
            category: 'snacks',
            description: 'Bread stuffed with spiced filling and fried',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});